language: php
matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: trusty
    - php: 7
      dist: trusty
    - php: 7.1
      dist: trusty
    - php: 7.2
      dist: trusty
    - php: 7.3
      dist: trusty
  
before_script:
  - composer self-update && composer install --no-interaction

script:
  - ./vendor/bin/phpunit
